FROM python:3.9-slim

WORKDIR /app

COPY frontend_service.py .
COPY templates/ templates/

RUN pip install fastapi uvicorn requests jinja2

EXPOSE 8000 3030

CMD ["python", "frontend_service.py"]
